# Site settings
title: Nikola Andrić
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: '/Nikola_Andric_Website'
profilepic: '/images/NikolaAndro.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Nikola Andrić'
  email: dzonikika@yahoo.com
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  NikolaAndro
  linkedin_username:  nikola-andrić-128597179
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
